name: "SAST Quality Gate (CodeQL)"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  analyze:
    name: Análisis de Seguridad Estático (SAST)
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    - name: Configurar JDK (Entorno Java para BodgeIt)
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Inicializar CodeQL (Reglas Estrictas)
      uses: github/codeql-action/init@v3
      with:
        languages: java
        queries: security-extended,security-and-quality

    - name: Parche para compilación Legacy (Crear carpeta faltante)
      run: mkdir -p build/WEB-INF/classes

    - name: Construcción Automática
      uses: github/codeql-action/autobuild@v3

    - name: Ejecutar Análisis SAST y Quality Gate
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:java"
